use_frameworks!

target 'TestPodChuck_Example' do
  pod 'TestPodChuck', :path => '../'

  target 'TestPodChuck_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
